# Generated by Django 3.1.7 on 2021-04-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50)),
                ('stateAbbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attractionName', models.CharField(max_length=200)),
                ('homeState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_attractions.states')),
            ],
        ),
    ]
