# Generated by Django 3.1.4 on 2021-04-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='stateName',
            new_name='StateName',
        ),
    ]
