# Generated by Django 3.1.4 on 2021-04-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0002_auto_20210414_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='states',
            old_name='StateName',
            new_name='stateName',
        ),
    ]
