# Generated by Django 3.1.4 on 2021-04-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0003_auto_20210414_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='attractionName',
            field=models.CharField(max_length=200, verbose_name='Attraction Name'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='homeState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourist_attractions.states', verbose_name='Home State'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateAbbreviation',
            field=models.CharField(max_length=3, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='states',
            name='stateName',
            field=models.CharField(max_length=50, verbose_name='State Name'),
        ),
    ]
