# Generated by Django 3.1.4 on 2021-04-21 16:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('tourist_attractions', '0004_auto_20210414_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
